### ISSUE TITLE
Error in Lambda Function

### ISSUE THREAD

**Issue by rahulb-218** [aws-samples/aws-lambda-sap-odp-extractor#2]
Hello,

I am trying to use ODP on AWS , but when i test the AWS lambda function, i get the following error

`{
  "statusCode": 200,
  "body": {
    "success": false,
    "message": "Expecting value: line 1 column 1 (char 0)",
    "traceback": "Traceback (most recent call last):\n  File \"/opt/python/extractor.py\", line 69, in extract\n    _extract(\" \",True)\n  File \"/opt/python/extractor.py\", line 96, in _extract\n    sapresponsebody = json.loads(sapresponse.text)\n  File \"/var/lang/lib/python3.6/json/__init__.py\", line 354, in loads\n    return _default_decoder.decode(s)\n  File \"/var/lang/lib/python3.6/json/decoder.py\", line 339, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File \"/var/lang/lib/python3.6/json/decoder.py\", line 357, in raw_decode\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
    "data": null,
    "numberofrecs": 0
  }
}`

Has anyone encountered this before?

**Comment by kumarrk21** [comment]
Can you check if you are getting a response from the OData service using a tool like Postman? It seems like either you are not able to reach the SAP application or you are receiving an error payload from the backend.

**Comment by rahulb-218** [comment]
I tried this using Postman, got the following message, seems like it is working

![postman](https://user-images.githubusercontent.com/64947663/81299145-66f2c580-9093-11ea-9a5e-1ab09302eebc.jpg)

Please let me know if you need any more information.

Thanks,

**Comment by kumarrk21** [comment]
It does seem like the response from the SAP HTTP call in extractor.py is failing. This could be because of multiple reasons - Incorrect password, incorrect environment values in lambda etc. You could add additional debug/logs in '_make_http_call_to_sap' procedure in the extractor.py. You should find the extractor.py the /lib/glue/aws-sap-odp-extractor/extractor folder. First thing to rule out is if Lambda is unable to make the HTTP call. Can you double check if you are use the right authentication and the right service details? Also double check the environment values. Add additional logs, redeploy CDK and check what response you are getting back from SAP. You might want to delete entries in the metadata dynomodb table if there are entries in it for this serviec.
